# Generated by Django 5.1.7 on 2025-04-11 19:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="capacity",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000001"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90.0")),
                    django.core.validators.MaxValueValidator(Decimal("90.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180.0")),
                    django.core.validators.MaxValueValidator(Decimal("180.0")),
                ],
            ),
        ),
    ]
