# Generated by Django 5.1.7 on 2025-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_device_capacity_alter_device_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuerequest",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issuerequest",
            name="period_of_production",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="issuerequest",
            name="upload_file",
            field=models.FileField(null=True, upload_to="issue-requests/"),
        ),
    ]
