# Generated by Django 5.1.7 on 2025-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_issuerequest_notes_issuerequest_period_of_production_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
