# Generated by Django 5.1.7 on 2025-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_device_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="commissioning_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
