# Generated by Django 5.1.7 on 2025-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_device_commissioning_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
