# Generated by Django 5.1.7 on 2025-04-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_device_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="auxiliary_energy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="auxiliary_energy_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="carbon_offset_registration",
            field=models.CharField(
                blank=True,
                help_text="Carbon offset or energy tracking scheme registration ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="connection_voltage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="electricity_import_details",
            field=models.TextField(
                blank=True,
                help_text="Details of how the site can import electricity by means other than through the meter(s)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="funding_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="grid_connection_details",
            field=models.TextField(
                blank=True,
                help_text="If not connected directly to the grid, specify the circumstances",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="labelling_scheme",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="meter_ids",
            field=models.TextField(
                blank=True, help_text="Meter or Measurement ID(s)", null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="network_owner",
            field=models.CharField(
                blank=True,
                help_text="Owner of the network to which the Production Device is connected",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="onsite_consumer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="onsite_consumer_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="public_funding",
            field=models.CharField(
                choices=[
                    ("No", "No"),
                    ("Investment", "Investment"),
                    ("Production", "Production"),
                ],
                default="No",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="volume_evidence_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="volume_evidence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Metering", "Metering data"),
                    ("Invoice", "Contract sales invoice"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
